// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moditor.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Moditor.Api.Migrations
{
    [DbContext(typeof(ModitorDbContext))]
    [Migration("20260809010623_RenameConflictToCompatibilityAndFixDeleteBehaviors")]
    partial class RenameConflictToCompatibilityAndFixDeleteBehaviors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Moditor.Api.Models.Mod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<bool>("HasFomod")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<int>("LoadOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NexusId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Mods");
                });

            modelBuilder.Entity("Moditor.Api.Models.ModCompatibility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompatible")
                        .HasColumnType("boolean");

                    b.Property<int>("ModIdA")
                        .HasColumnType("integer");

                    b.Property<int>("ModIdB")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("PatchNexusId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModIdA");

                    b.HasIndex("ModIdB");

                    b.ToTable("ModConflicts");
                });

            modelBuilder.Entity("Moditor.Api.Models.ModOrderRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ModId")
                        .HasColumnType("integer");

                    b.Property<int>("RelatedModId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModId");

                    b.HasIndex("RelatedModId");

                    b.ToTable("ModOrderRules");
                });

            modelBuilder.Entity("Moditor.Api.Models.ModRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ModId")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredModId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModId");

                    b.ToTable("ModRequirements");
                });

            modelBuilder.Entity("Moditor.Api.Models.ModCompatibility", b =>
                {
                    b.HasOne("Moditor.Api.Models.Mod", "ModA")
                        .WithMany()
                        .HasForeignKey("ModIdA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Moditor.Api.Models.Mod", "ModB")
                        .WithMany()
                        .HasForeignKey("ModIdB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModA");

                    b.Navigation("ModB");
                });

            modelBuilder.Entity("Moditor.Api.Models.ModOrderRule", b =>
                {
                    b.HasOne("Moditor.Api.Models.Mod", "Mod")
                        .WithMany()
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Moditor.Api.Models.Mod", "RelatedMod")
                        .WithMany()
                        .HasForeignKey("RelatedModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mod");

                    b.Navigation("RelatedMod");
                });

            modelBuilder.Entity("Moditor.Api.Models.ModRequirement", b =>
                {
                    b.HasOne("Moditor.Api.Models.Mod", "Mod")
                        .WithMany()
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mod");
                });
#pragma warning restore 612, 618
        }
    }
}
